/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Nov 15 03:56:07 GMT 2025
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/1_/dl3rw8793151ytqw4g_f7dfm0000gn/T/"); 
    java.lang.System.setProperty("user.country", "NG"); 
    java.lang.System.setProperty("user.dir", "/Users/kennie/Downloads/EECS 4313/commons-cli"); 
    java.lang.System.setProperty("user.home", "/Users/kennie"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kennie"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.Converter",
      "org.junitpioneer.jupiter.cartesian.CartesianArgumentsProvider",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.apache.commons.cli.ParseException",
      "org.junitpioneer.jupiter.json.JsonClasspathSourceArgumentsProvider",
      "org.junitpioneer.jupiter.cartesian.CartesianParameterArgumentsProvider",
      "org.apache.commons.cli.TypeHandler",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.cli.ParseException",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.CanExecuteFileFilter",
      "org.apache.commons.cli.Option",
      "org.apache.commons.text.similarity.JaroWinklerDistance",
      "org.apache.commons.text.similarity.LevenshteinResults",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.AbstractPathFencedLookup",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.junitpioneer.jupiter.json.JsonClasspathSourceArgumentsProvider",
      "org.apache.commons.text.lookup.XmlDecoderStringLookup",
      "org.apache.commons.text.StrLookup$SystemPropertiesStrLookup",
      "org.apache.commons.text.StrLookup",
      "org.apache.commons.text.StrLookup$MapStrLookup",
      "org.apache.commons.text.StrLookup$ResourceBundleLookup",
      "org.apache.commons.text.lookup.UrlDecoderStringLookup",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.text.similarity.JaccardDistance",
      "org.apache.commons.text.similarity.JaccardSimilarity",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction$ByteArrayUrlStreamHandler",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.junitpioneer.jupiter.CartesianValueArgumentsProvider",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.text.similarity.SimilarityCharacterInput",
      "org.apache.commons.text.similarity.LevenshteinDistance",
      "org.apache.commons.io.file.CopyDirectoryVisitor",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.io.file.Counters$BigIntegerCounter"
    );
  }
}
