/*
 * This file was automatically generated by EvoSuite
 * Sat Nov 15 03:48:50 GMT 2025
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setArgs((-818));
      option0.requiresArg();
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setValueSeparator('O');
      option0.setArgs(1238);
      option0.processValue("NO_ARGS_ALLOWED");
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setOptionalArg(true);
      option0.setArgs(0);
      option0.acceptsArg();
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(true);
      option_Builder1.optionalArg(true);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator('w');
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.required(false);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.isValuesEmpty();
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option("TN", "Deprecated", true, "Die5\"|?FA931FX1r");
      option0.processValue("TN");
      option0.isValuesEmpty();
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option option0 = new Option((String) null, "org.apache.commons.cli.Option", true, "");
      option0.setOptionalArg(true);
      option0.hasOptionalArg();
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setArgs((-818));
      option0.setOptionalArg(true);
      option0.processValue("NO_ARGS_ALLOWED");
      option0.getValuesList();
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setValueSeparator('O');
      option0.getValueSeparator();
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.getValue((String) null);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", true, "E[Mo?~7:=^-_4");
      option0.processValue("");
      option0.getValue("NO_ARGS_ALLOWED");
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", true, "E[Mo?~7:=^-_4");
      option0.processValue("");
      option0.getValue(0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("ODF_w");
      option_Builder0.since("ODF_w");
      Option option0 = option_Builder0.get();
      option0.getSince();
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option.Builder option_Builder2 = option_Builder1.since("");
      Option option0 = option_Builder2.get();
      option0.getSince();
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.getOpt();
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.getLongOpt();
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.getLongOpt();
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.getKey();
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.getId();
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option option0 = new Option("converterMap", "converterMap", true, "converterMap");
      option0.getDescription();
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.getDescription();
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("NeZ3");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option option0 = new Option("u", "u", true, "");
      option0.setArgs(0);
      option0.getArgs();
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option option0 = new Option("TN", "Deprecated", true, "Die5\"|?FA931FX1r");
      option0.getArgs();
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option option0 = new Option("daev", "sdmD[5v[op<_RW%");
      option0.setArgName("fe=qt3cXj@Y}fRV#L");
      option0.getArgName();
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.setArgName("");
      option0.getArgName();
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option("daev", "sdmD[5v[op<_RW%");
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        option0.setType(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", "", true, "2a]9gZSEJ\"e\"\"/Zb");
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.processValue("Deprecated");
      try { 
        option0.getValue((-2));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("~/GP[ ~Q");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name '~'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option(" since ", true, " since ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Illegal option name ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", "", false, (String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("9HAu(ZM5Q|", "9HAu(ZM5Q|");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option '9HAu(ZM5Q|' contains an illegal character : '('.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.isDeprecated();
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      String string0 = "\\u";
      option_Builder0.longOpt(string0);
      Option option0 = option_Builder1.get();
      option0.isDeprecated();
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = new Option("Deprecated", "Deprecated", false, "Deprecated");
      option0.hasValueSeparator();
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = new Option((String) null, "Empty option name.", false, (String) null);
      option0.hasArgs();
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option("daev", "sdmD[5v[op<_RW%");
      option0.setArgs(39);
      option0.hasArgs();
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      option0.hasArg();
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option option0 = new Option("TN", "Deprecated", true, "Die5\"|?FA931FX1r");
      option0.hasArg();
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.hasArg();
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      option0.getValue();
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option((String) null, "", false, "");
      option0.getKey();
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Class<Integer> class0 = Integer.class;
      option0.setType(class0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.toString();
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.deprecated();
      Option option0 = option_Builder1.get();
      option0.toString();
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("ghn");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.toDeprecatedString();
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      option0.requiresArg();
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setOptionalArg(true);
      option0.requiresArg();
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setValueSeparator('O');
      option0.setArgs((-818));
      option0.setOptionalArg(true);
      option0.processValue("NO_ARGS_ALLOWED");
      option0.getValue(1);
      assertEquals((-818), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setValueSeparator('O');
      option0.setArgs((-818));
      // Undeclared exception!
      try { 
        option0.processValue("NO_ARGS_ALLOWED");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.deprecated();
      Option option0 = option_Builder1.get();
      String string0 = option0.toDeprecatedString();
      assertEquals("Option 'null''ghn': Deprecated", string0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setValueSeparator('O');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('O', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      boolean boolean0 = option0.hasLongOpt();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArgs();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option("fnAk", "`V[h-SA+>xQVu");
      option0.setArgs(1954);
      option0.toString();
      assertEquals(1954, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder0.argName(": ");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      boolean boolean0 = option0.hasArgName();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      option0.processValue(": ");
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArg());
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String[] stringArray0 = option0.getValues();
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.processValue("Deprecated");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setArgs((-818));
      option0.setOptionalArg(true);
      option0.processValue("NO_ARGS_ALLOWED");
      option0.getValue("");
      assertEquals((-818), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.getValue(0);
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.setArgs((-818));
      option0.setOptionalArg(true);
      option0.processValue("NO_ARGS_ALLOWED");
      try { 
        option0.getValue(1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 1, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      String string0 = option0.getValue("NO_ARGS_ALLOWED");
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      option_Builder0.hasArg();
      Option option0 = option_Builder1.get();
      option0.processValue(": ");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      String string0 = option0.getKey();
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option option0 = new Option("Deprecated", (String) null);
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("value");
      Option option1 = option_Builder1.get();
      boolean boolean0 = option0.equals(option1);
      assertEquals((-1), option1.getArgs());
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      Option option1 = new Option((String) null, "[ Option null :: null :: class java.lang.String ]", false, (String) null);
      boolean boolean0 = option1.equals(option0);
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Object object0 = option0.clone();
      boolean boolean0 = object0.equals(option0);
      assertTrue(boolean0);
      assertNotSame(object0, option0);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      boolean boolean0 = option0.equals(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.equals("[ Option null ghn Deprecated[ARG...] :: *wJ2W>1C.3Yfm :: class java.lang.String ]");
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      assertEquals(1, option0.getArgs());
      
      option0.processValue("R*LOwN:xB-Ifp(,3");
      boolean boolean0 = option0.requiresArg();
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setLongOpt("org.apache.commons.cli.Option$1");
      boolean boolean0 = option0.hasLongOpt();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option option0 = new Option("Deprecated", (String) null);
      option0.getOpt();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("ghn");
      Option option0 = option_Builder1.get();
      option0.getType();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option option0 = new Option("converterMap", "converterMap", true, "converterMap");
      // Undeclared exception!
      try { 
        option0.addValue("converterMap");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      String string0 = option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option option0 = new Option("Deprecated", (String) null);
      option0.hashCode();
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.isRequired();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option("converterMap", "converterMap", true, "converterMap");
      option0.getSince();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.getDescription();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option("Deprecated", (String) null);
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.clearValues();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.getDeprecated();
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.getValueSeparator();
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertFalse(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option option0 = new Option("NO_ARGS_ALLOWED", false, "E[Mo?~7:=^-_4");
      option0.hasOptionalArg();
      assertEquals("E[Mo?~7:=^-_4", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option("Deprecated", (String) null);
      option0.setDescription("Deprecated");
      assertEquals((-1), option0.getArgs());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option("B6E", "org.apache.commons.cli.TypeHandler", false, "B6E");
      Converter<?, ?> converter0 = option0.getConverter();
      option0.setConverter(converter0);
      Converter<?, ?> converter1 = option0.getConverter();
      assertEquals("org.apache.commons.cli.TypeHandler", option0.getLongOpt());
      assertEquals("B6E", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertNotNull(converter1);
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.getValuesList();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.setRequired(true);
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Class<Option> class0 = Option.class;
      Option.Builder option_Builder1 = option_Builder0.type(class0);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      assertSame(option_Builder1, option_Builder2);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.desc("*wJ2W>1C.3Yfm");
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs((-1));
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      Option.Builder option_Builder2 = option_Builder1.longOpt("");
      Option option0 = option_Builder2.get();
      assertTrue(option0.hasArg());
      
      option0.processValue("");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Option.Builder option_Builder0 = Option.builder();
      Converter<?, ?> converter0 = option0.getConverter();
      assertNotNull(converter0);
      
      option_Builder0.converter(converter0);
      assertEquals(1, option0.getArgs());
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.required();
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder((String) null);
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      assertSame(option_Builder1, option_Builder0);
  }
}
